{{/*
namespace.yaml
Crea el namespace si global.namespace está definido.
Si está vacío, se usa el namespace del release (-n flag de helm).
*/}}
{{- if .Values.global.namespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.global.namespace }}
  labels:
    {{- include "wordpress-iso27001.labels" . | nindent 4 }}
    # Pod Security Admission — A.9.4 ISO 27001
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
{{- end }}
