{{/*
serviceaccount.yaml
ServiceAccount con mínimo privilegio — ISO 27001 A.9.2.3
*/}}
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress-iso27001.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress-iso27001.labels" . | nindent 4 }}
automountServiceAccountToken: false   # No montar token a menos que sea necesario
{{- end }}
